# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='reviewer',
        ),
    ]
