# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
